services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: orocommerce-php
    volumes:
      - ./orocommerce-application:/var/www/orocommerce
      - ./php/conf.d/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini
    networks:
      - orocommerce-net
    environment:
      ORO_ENV: dev
      ORO_DEBUG: "1"

  nginx:
    image: nginx:1.25
    container_name: orocommerce-nginx
    ports:
      - "8080:80"
    volumes:
      - ./orocommerce-application:/var/www/orocommerce
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - orocommerce-net

  pgsql:
    image: oroinc/pgsql:17.4-alpine
    environment:
      POSTGRES_USER: oro_db_user
      POSTGRES_DB: oro_db
      POSTGRES_PASSWORD: oro_db_pass
      POSTGRES_ROOT_PASSWORD: oro_db_pass
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - orocommerce-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - orocommerce-net

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    networks:
      - orocommerce-net

networks:
  orocommerce-net:

volumes:
  db_data:
  postgres:
